let musicOn=false,musicState='idle',trackIndex=0,shuffleOn=false,musicRequest=0,wantsMusic=true,usingFallback=false;
const ambient=document.getElementById('ambient-audio');
const musicText={zh:{idle:'C418 · Minecraft',loading:'正在載入…',playing:'C418 · 播放中',paused:'已暫停',blocked:'點任一選項開啟音樂',error:'載入失敗 · 可切下一首',fallback:'原創鋼琴 · 播放中'},en:{idle:'C418 · Minecraft',loading:'Loading…',playing:'C418 · Playing',paused:'Paused',blocked:'Tap any option for sound',error:'Unavailable · Try next track',fallback:'Original piano · Playing'}};
function getTrack(){return usingFallback?{title:lang==='zh'?'原創方塊鋼琴':'Original block piano',src:'assets/fred-ambient.mp3'}:MUSIC_TRACKS[trackIndex]}
function refreshMusicPanel(){document.getElementById('playback-mode').textContent=lang==='zh'?(shuffleOn?'隨機連播 · 播完自動換一首':'順序連播 · 播完自動下一首，最後一首回到第一首'):(shuffleOn?'Shuffle · Automatically plays another track':'Autoplay · Next track, then back to the first after the last');const title=getTrack().title;document.getElementById('track-title').textContent=title;document.getElementById('music-status').textContent=musicText[lang][musicState==='playing'&&usingFallback?'fallback':musicState];document.getElementById('play-pause').textContent=musicOn?'Ⅱ':'▶';document.getElementById('play-pause').setAttribute('aria-label',lang==='zh'?(musicOn?'暫停':'播放'):(musicOn?'Pause':'Play'));document.getElementById('play-pause').setAttribute('aria-pressed',String(musicOn));document.querySelector('.music-dock').classList.toggle('is-playing',musicOn);document.getElementById('shuffle').setAttribute('aria-pressed',String(shuffleOn));document.getElementById('local-fallback').hidden=musicState!=='error';const labels={'previous-track':['上一首','Previous track'],'next-track':['下一首','Next track'],'toggle-playlist':['開啟歌單','Open playlist'],'close-playlist':['關閉歌單','Close playlist'],'track-summary':['開啟音樂歌單','Open music playlist']};Object.entries(labels).forEach(([id,v])=>document.getElementById(id).setAttribute('aria-label',v[lang==='zh'?0:1]));document.getElementById('track-list').innerHTML=MUSIC_TRACKS.map((v,i)=>`<button class="track-option ${i===trackIndex&&!usingFallback?'selected':''}" data-track="${i}" aria-current="${i===trackIndex&&!usingFallback?'true':'false'}"><span class="track-num">${String(i+1).padStart(2,'0')}</span><span><strong>${v.title}</strong><small>C418 · Minecraft</small></span><span aria-hidden="true">${i===trackIndex&&!usingFallback?'▸':'♫'}</span></button>`).join('')}
function updateMusicLabels(){document.querySelectorAll('.main-menu .music-toggle [data-i18n]').forEach(el=>el.textContent=t('music'));if(current==='settings'){const b=document.querySelector('.settings-list .music-toggle');if(b)b.textContent=lang==='zh'?'選擇音樂':'Choose music'}}
function setMusicState(state){musicState=state;musicOn=state==='playing';refreshMusicPanel();updateMusicLabels()}
function setPlaylist(open){document.getElementById('music-panel').hidden=!open;for(const id of ['toggle-playlist','track-summary'])document.getElementById(id).setAttribute('aria-expanded',String(open))}
function loadTrack(){ambient.loop=false;ambient.src=getTrack().src;ambient.load();if(!usingFallback)savePref('fred-track',String(trackIndex))}
function playMusic(){if(ambient.error)loadTrack();wantsMusic=true;const request=++musicRequest;setMusicState('loading');ambient.muted=false;let promise;try{promise=ambient.play()}catch(e){setMusicState('error');return}promise?.catch(e=>{if(request!==musicRequest||e.name==='AbortError')return;setMusicState(e.name==='NotAllowedError'?'blocked':'error')})}
function stopMusic(){wantsMusic=false;musicRequest++;ambient.pause();setMusicState('paused')}
function togglePlayback(){musicOn||(!ambient.paused&&musicState==='loading')?stopMusic():playMusic()}
function toggleMusic(){setPlaylist(document.getElementById('music-panel').hidden);if(!musicOn)playMusic()}
function selectTrack(index){musicRequest++;usingFallback=false;trackIndex=index;loadTrack();playMusic()}
function advanceTrack(delta=1){let next;if(shuffleOn&&MUSIC_TRACKS.length>1){next=(trackIndex+1+Math.floor(Math.random()*(MUSIC_TRACKS.length-1)))%MUSIC_TRACKS.length}else next=(trackIndex+delta+MUSIC_TRACKS.length)%MUSIC_TRACKS.length;selectTrack(next)}
function syncBackground(){const v=document.getElementById('world-video');if(!v)return;if(motionOn&&!document.hidden){v.muted=true;v.play()?.catch(()=>{})}else v.pause()}
function initMusic(){const saved=Number(readPref('fred-track','0'));trackIndex=Number.isInteger(saved)&&saved>=0&&saved<MUSIC_TRACKS.length?saved:0;const volume=Number(readPref('fred-volume','60'));ambient.volume=Number.isFinite(volume)?Math.max(0,Math.min(100,volume))/100:.6;document.getElementById('music-volume').value=Math.round(ambient.volume*100);document.getElementById('volume-value').textContent=Math.round(ambient.volume*100)+'%';loadTrack();refreshMusicPanel();playMusic();syncBackground()}
ambient.addEventListener('playing',()=>setMusicState('playing'));ambient.addEventListener('pause',()=>{if(wantsMusic)setMusicState('paused')});ambient.addEventListener('waiting',()=>{if(wantsMusic)setMusicState('loading')});ambient.addEventListener('error',()=>setMusicState('error'));ambient.addEventListener('ended',()=>{if(wantsMusic)advanceTrack()});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.track!==undefined)selectTrack(Number(b.dataset.track));if(b?.id==='previous-track'){if(ambient.currentTime>3){ambient.currentTime=0;playMusic()}else advanceTrack(-1)}if(b?.id==='next-track')advanceTrack();if(b?.id==='play-pause')togglePlayback();if(['toggle-playlist','track-summary'].includes(b?.id))setPlaylist(document.getElementById('music-panel').hidden);if(b?.id==='close-playlist')setPlaylist(false);if(b?.id==='shuffle'){shuffleOn=!shuffleOn;refreshMusicPanel()}if(b?.id==='local-fallback'){musicRequest++;usingFallback=true;loadTrack();playMusic()}if(!e.target.closest('.music-dock,.track-panel,.music-toggle')){setPlaylist(false);if(wantsMusic&&!musicOn&&musicState==='blocked')playMusic();syncBackground()}});
document.getElementById('music-volume').addEventListener('input',e=>{ambient.volume=Number(e.target.value)/100;document.getElementById('volume-value').textContent=e.target.value+'%';savePref('fred-volume',e.target.value)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')setPlaylist(false)});document.addEventListener('visibilitychange',syncBackground);
