'use strict';
const money=n=>n.toLocaleString('zh-TW');
const modules=[
 {id:'leads',name:'看車預約＋收購／估車申請',price:4000,standard:5000,desc:'預約申請、照片上傳、後台狀態與 Email 通知；估車由你人工報價。'},
 {id:'catalog',name:'零件展示與詢價',price:8000,standard:10000,desc:'商品分類、規格、適用車款與管理後台，先詢價再成交。'},
 {id:'checkout',name:'零件購物車、金流與訂單',price:20000,standard:25000,desc:'一家金流、庫存與訂單管理。需先有零件展示，選取時自動加上。'},
 {id:'ai',name:'網站 AI 客服',price:16000,standard:20000,desc:'站上車款查詢、需求彙整、預約引導及最多 50 題初始問答；用量另計。'},
 {id:'languages',name:'多語言網站（共 3 種語言）',price:8000,standard:10000,desc:'繁中＋兩種外語，含語言切換、翻譯欄位與初始內容翻譯草稿；語言開工前確認。'},
 {id:'translation',name:'AI 客服翻譯',price:4000,standard:5000,desc:'同一組 3 語文字問答、中文需求摘要與回覆翻譯草稿。需網站 AI 客服，選取時自動加上。'},
 {id:'finance',name:'購車月付試算',price:2400,standard:3000,desc:'頭期款、期數與利率試算，不含銀行核貸串接。'},
 {id:'compare',name:'車款比較＋本機收藏',price:4000,standard:5000,desc:'比較車款規格，收藏保存在同一瀏覽器，不含跨裝置會員。'},
 {id:'crm',name:'客戶追蹤管理',price:8000,standard:10000,desc:'需求、備註、進度、回訪日期與資料匯出。'}
];
const plans={
 base:{name:'基礎車庫版',price:24000,standard:30000,includes:[],duration:'3–4 週',desc:'把車款和介紹放上去，客人點進來就能看。',badge:'8 折優惠',features:['品牌官網與線上車庫','車款篩選、獨立介紹頁','自行上下架與更新車況','交車案例、社群聯絡入口']},
 growth:{name:'接單實用版',price:36000,standard:45000,includes:['leads','catalog'],duration:'4–6 週',desc:'加上看車預約、估車申請和零件詢價。',badge:'推薦起步 · 8 折',features:['包含基礎車庫版全部功能','看車／試乘預約申請','收購、寄賣與估車申請','零件展示、詢價與後台']},
 commerce:{name:'零件商城版',price:49000,standard:70000,includes:['leads','catalog','checkout'],duration:'6–8 週',desc:'零件可以直接買，你從後台處理訂單。',badge:'專屬優惠 7 折',features:['包含接單實用版全部功能','購物車、訪客結帳與金流','商品庫存、付款出貨管理','宅配費設定與到店取貨']},
 ai:{name:'AI 整合版',price:63000,standard:90000,includes:['leads','catalog','checkout','ai','languages','translation'],gifts:['languages','translation'],duration:'8–10 週',desc:'商城、AI 一起做，多語言和翻譯直接送。',badge:'專屬優惠 7 折',features:['包含零件商城版全部功能','網站 AI 客服與車款推薦','客人需求彙整與聯絡引導','用量紀錄、上限與真人引導','贈送｜多語言網站（3 語）','贈送｜AI 客服翻譯']}
};
let selectedPlan='growth';let extras=new Set();
const $=id=>document.getElementById(id);
function totals(){const p=plans[selectedPlan];let price=p.price,standard=p.standard;for(const m of modules)if(extras.has(m.id)&&!p.includes.includes(m.id)){price+=m.price;standard+=m.standard;}return{price,standard,saved:standard-price};}
function selectPlan(id){if(!plans[id])throw new Error('未知方案');selectedPlan=id;extras=new Set();$('plan-select').value=id;render();}
function toggleModule(id,checked){const m=modules.find(x=>x.id===id);if(!m)throw new Error('未知功能');const p=plans[selectedPlan];if(p.includes.includes(id))return;if(checked){extras.add(id);if(id==='checkout'&&!p.includes.includes('catalog'))extras.add('catalog');if(id==='translation'&&!p.includes.includes('ai'))extras.add('ai');}else{extras.delete(id);if(id==='catalog')extras.delete('checkout');if(id==='ai')extras.delete('translation');}render();}
function render(){const p=plans[selectedPlan],t=totals();$('plan-cards').innerHTML=Object.entries(plans).map(([id,plan],i)=>`<article class="plan ${i>1?'premium':''} ${selectedPlan===id?'selected':''}"><div class="plan-top"><span class="plan-index">PLAN 0${i+1}</span><span class="badge">${plan.badge}</span></div><h3>${plan.name}</h3><p class="plan-desc">${plan.desc}</p><p class="was">建議標準報價 <s>$${money(plan.standard)}</s></p><p class="price"><small>NT$</small>${money(plan.price)}</p><p class="save-pill">這次優惠省下 $${money(plan.standard-plan.price)}</p><ul>${plan.features.map(f=>`<li>${f}</li>`).join('')}</ul><p class="duration">預估製作 ${plan.duration} · 一次性建置</p><button class="button plan-button" data-plan="${id}" aria-pressed="${selectedPlan===id}">${selectedPlan===id?'已選擇此方案 ✓':'選擇並搭配功能'}</button></article>`).join('');
 $('modules').innerHTML=modules.map(m=>{const included=p.includes.includes(m.id),gift=p.gifts?.includes(m.id),checked=included||extras.has(m.id);return `<label class="module ${included?'included':''} ${gift?'gift-module':''} ${checked?'checked':''}"><input type="checkbox" data-module="${m.id}" ${checked?'checked':''} ${included?'disabled':''} aria-label="${m.name}${gift?'（免費贈送）':included?'（方案已包含）':''}"><div class="module-info"><strong>${m.name}</strong><p>${m.desc}</p></div><span class="module-price">${gift?'免費贈送':included?'方案已包含':'+ $'+money(m.price)}${gift?`<small>加購價 $${money(m.price)}</small>`:included?'':`<small>標準 $${money(m.standard)} · 8 折</small>`}</span></label>`}).join('');
 $('summary-title').textContent=p.name+(extras.size?'＋加購':'');$('total').textContent=money(t.price);$('saved').textContent='NT$'+money(t.saved);$('deposit').textContent='$'+money(t.price*.4);$('progress').textContent='$'+money(t.price*.4);$('balance').textContent='$'+money(t.price*.2);$('mobile-plan').textContent=p.name+(extras.size?'＋加購':'');$('mobile-price').textContent='NT$'+money(t.price);$('quote-lines').innerHTML=`<div class="quote-line"><span>${p.name}</span><strong>$${money(p.price)}</strong></div>`+modules.filter(m=>extras.has(m.id)&&!p.includes.includes(m.id)).map(m=>`<div class="quote-line"><span>${m.name}</span><strong>$${money(m.price)}</strong></div>`).join('');$('copy-status').textContent='';$('copy-fallback').hidden=true;$('gift-summary').hidden=!p.gifts;
 const needed=new Set([...p.includes,...extras]);const options=Object.entries(plans).filter(([id,plan])=>id!==selectedPlan&&[...needed].every(k=>plan.includes.includes(k))&&plan.price<t.price).sort((a,b)=>a[1].price-b[1].price);$('better-deal').hidden=!options.length;if(options.length){const[id,best]=options[0];$('better-deal').innerHTML=`你選的這些功能，改選「${best.name}」只要 NT$${money(best.price)}，可再省 NT$${money(t.price-best.price)}。<button data-upgrade="${id}">那我改選這個 →</button>`;}
}
function quoteText(){const p=plans[selectedPlan],t=totals();return `我看好了，想跟你聊這個網站組合：\n\n方案：${p.name}\n方案優惠價：NT$${money(p.price)}\n已包含：品牌官網與線上車庫${p.includes.length?'、'+modules.filter(m=>p.includes.includes(m.id)&&!p.gifts?.includes(m.id)).map(m=>m.name).join('、'):''}${p.gifts?'\n免費贈送：多語言網站（共 3 語）＋AI 客服翻譯，兩項加購優惠價合計 NT$12,000，贈送建置費不含模型用量。':''}\n加購：${extras.size?'\n'+modules.filter(m=>extras.has(m.id)).map(m=>`・${m.name} NT$${money(m.price)}`).join('\n'):'無'}\n\n一次性建置估價：NT$${money(t.price)}\n方案及付費加購折扣省下（不含贈品價值）：NT$${money(t.saved)}\n付款：訂金 NT$${money(t.price*.4)}／測試版 NT$${money(t.price*.4)}／驗收 NT$${money(t.price*.2)}\n\n主機、網址、AI 用量與金流費另計；稅額與最終需求、時程於正式報價確認。\n提案日期：2026/09/27，有效至 2026/10/11。`}
$('plan-cards').addEventListener('click',e=>{const b=e.target.closest('[data-plan]');if(b){selectPlan(b.dataset.plan);$('configure').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}});
$('plan-select').addEventListener('change',e=>selectPlan(e.target.value));
$('modules').addEventListener('change',e=>{const id=e.target.dataset.module;if(id){toggleModule(id,e.target.checked);document.querySelector(`[data-module="${id}"]`)?.focus({preventScroll:true});}});
$('better-deal').addEventListener('click',e=>{const b=e.target.closest('[data-upgrade]');if(b){selectPlan(b.dataset.upgrade);$('plan-select').focus({preventScroll:true});}});
$('copy-quote').addEventListener('click',async()=>{const text=quoteText();try{await navigator.clipboard.writeText(text);$('copy-status').textContent='已複製好了，貼到 LINE 給我就可以。';}catch{$('copy-fallback').value=text;$('copy-fallback').hidden=false;$('copy-fallback').focus();$('copy-fallback').select();$('copy-status').textContent='請長按或全選下方清單，手動複製後貼到 LINE。';}});
render();
if(document.modelContext?.registerTool){const life=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'configure_website_quote',title:'搭配網站報價',description:'選擇網站提案方案與加購功能，更新畫面的估價。不送出訂單或聯絡訊息。',inputSchema:{type:'object',properties:{plan:{type:'string',enum:Object.keys(plans)},addons:{type:'array',items:{type:'string',enum:modules.map(m=>m.id)},uniqueItems:true}},required:['plan','addons'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!plans[input.plan]||!Array.isArray(input.addons)||input.addons.some(id=>!modules.some(m=>m.id===id)))throw new Error('請提供有效的方案及功能代碼。');selectPlan(input.plan);for(const id of input.addons)toggleModule(id,true);return{plan:plans[selectedPlan].name,addons:[...extras],gifts:plans[selectedPlan].gifts??[],currency:'TWD',...totals(),submitted:false};}},{signal:life.signal})).catch(()=>{});window.addEventListener('pagehide',()=>life.abort(),{once:true});}catch{}}
